#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""release/gen_locks.py -- generate a pip --require-hashes lock from a built
distribution directory (release build step; committed PRE-TAG).

  * armv7l: --dist-dir is the controlled offline WHEELHOUSE (resulting wheels).
  * aarch64: --dist-dir is `pip download --only-binary=:all: -r requirements.txt -d <dir>`
             (PyPI-published wheels).

Emits deterministic `name==version --hash=sha256:<hex>` lines covering every
distribution present, plus the requirements.txt sha256 in a header comment. This
is the ONLY supported way to (re)generate the platform locks; hand-editing is
forbidden (see the lock header)."""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys


def _parse_dist(fn: str):
    if fn.endswith(".whl"):
        parts = fn[:-4].split("-")
        if len(parts) >= 2:
            return parts[0].replace("_", "-").lower(), parts[1]
    m = re.match(r"^(.+?)-(\d[^-]*)\.tar\.gz$", fn)
    if m:
        return m.group(1).replace("_", "-").lower(), m.group(2)
    return None, None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="gen_locks.py")
    ap.add_argument("--dist-dir", required=True)
    ap.add_argument("--requirements", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args(argv)

    entries: dict = {}
    for fn in sorted(os.listdir(a.dist_dir)):
        path = os.path.join(a.dist_dir, fn)
        if not os.path.isfile(path):
            continue
        name, ver = _parse_dist(fn)
        if not name:
            continue
        h = hashlib.sha256(open(path, "rb").read()).hexdigest()
        entries.setdefault((name, ver), set()).add(h)

    if not entries:
        sys.stderr.write(f"gen_locks: no distributions found in {a.dist_dir!r}\n")
        return 1
    req_sha = hashlib.sha256(open(a.requirements, "rb").read()).hexdigest()
    lines = [
        "# GENERATED by release/gen_locks.py -- DO NOT hand-edit.",
        f"# requirements.txt sha256: {req_sha}",
    ]
    for (name, ver) in sorted(entries):
        hashes = " ".join(f"--hash=sha256:{h}" for h in sorted(entries[(name, ver)]))
        lines.append(f"{name}=={ver} {hashes}")
    with open(a.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {a.out}: {len(entries)} pinned distributions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
